### ISSUE TITLE
Can't use Llama 3.1 with MII, ImportError: cannot import name 'Conversation' from 'transformers'

### ISSUE THREAD

**Issue by chuyuanli** [microsoft/DeepSpeed-MII#514]
I have downloaded Llama-3.1 and wanted to try with MII for inference.
The latest llama model requires an upgrade for transformers.
However, after upgraded transformers to v4.43.2, I have issues when importing mii.
`import mii`.
Here is the error message:
```
Traceback (most recent call last):
  File "mii_server.py", line 40, in <module>
    import mii
  File "xxx/.envMII/lib/python3.10/site-packages/mii/__init__.py", line 7, in <module>
    from .legacy import MIIServer, MIIClient, mii_query_handle, deploy, terminate, DeploymentType, TaskType, aml_output_path, MIIConfig, ModelConfig, get_supported_models
  File "xxx/.envMII/lib/python3.10/site-packages/mii/legacy/__init__.py", line 7, in <module>
    from .client import MIIClient, mii_query_handle
  File "xxx/.envMII/lib/python3.10/site-packages/mii/legacy/client.py", line 12, in <module>
    from .method_table import GRPC_METHOD_TABLE
  File "xxx/.envMII/lib/python3.10/site-packages/mii/legacy/method_table.py", line 8, in <module>
    from transformers import Conversation
ImportError: cannot import name 'Conversation' from 'transformers' (xxx/.envMII/lib/python3.10/site-packages/transformers/__init__.py)
```

These are the mii related packages and upgraded transformer in my virtual env:
```
deepspeed          0.14.0+computecanada
deepspeed_kernels  0.1.0+bdb30fd.computecanada
deepspeed_mii      0.2.3+computecanada
transformers       4.43.2+computecanada
```

I used to use llama-3 with MII and it worked well.
I would like to know to fix this issue. Thanks.

**Comment by chuyuanli** [comment]
Fixed it by upgrading mii
